name: Generate snake animation

on:
  schedule:
    - cron: "* */12 * * *"

  workflow_dispatch:

  push:
    branches:
    - main

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: generate snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: dist/snake.svg?palette=github-dark
        env:
          GITHUB_TOKEN: ${{ secrets.SECRET_TOKEN }}



      - name: move and commit snake.svg into repo
        run: |
          mkdir -p assets
          mv dist/snake.svg assets/snake.svg
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add assets/snake.svg
          git commit -m "chore: update snake.svg [skip ci]" || echo "No changes to commit"
          git push
